# -*- coding: utf-8 -*-
"""Data_science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qwFmW7XORWIAm15QP7WVzsfWorJU0Rma
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv("/content/drive/My Drive/dataset/Heart_Disease_Prediction.csv")
df.head(15)

df2 = df[(df['Age']>35) &(df['Age']<45)]
df2

X = df.iloc[:, 0:13]
y = df.iloc[:,13]
X

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split (X,y, test_size=0.1)
X_train

from sklearn.svm import SVC

  clf = SVC()
  clf = clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)

from sklearn.metrics import accuracy_score

print(accuracy_score(y_pred, y_test) )